//#condition polish.android
// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Tue Mar 24 07:57:17 EET 2009
package de.enough.polish.android.location;

/**
 * The <code>LocationException</code> is thrown when a location API
 * specific error has occurred.
 * The detailed conditions when this exception is thrown are documented
 * in the methods that throw this exception.
 */
public class LocationException extends java.lang.Exception
{
	/**
	 * Constructs a <code>LocationException</code> with no detail message.
	 * <P>
	 * 
	 */
	public LocationException()
	{
		//TODO implement LocationException
	}

	/**
	 * Constructs a <code>LocationException</code> with the specified
	 * detail message.
	 * <P>
	 * 
	 * @param s - the detail message
	 */
	public LocationException(java.lang.String s)
	{
		//TODO implement LocationException
	}

}
