//#condition polish.android
// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Wed Jan 21 21:07:48 CET 2009
package de.enough.polish.android.media.protocol;

/**
 * 
 * A <CODE>ContentDescriptor</CODE> identifies media data containers.
 */
public class ContentDescriptor extends java.lang.Object
{
	//following variables are implicitely defined by getter- or setter-methods:
	private java.lang.String contentType;

	/**
	 * Create a content descriptor with the specified content type.
	 * <P>
	 * 
	 * @param contentType - The content type of this descriptor. If contentType is null, the type of the content is unknown.
	 */
	public ContentDescriptor(java.lang.String contentType)
	{
		//TODO implement ContentDescriptor
	}

	/**
	 * Obtain a string that represents the content type
	 * for this descriptor.
	 * If the content type is not known, <code>null</code> is returned.
	 * <P>
	 * 
	 * 
	 * @return The content type.
	 */
	public java.lang.String getContentType()
	{
		return this.contentType;
	}

}
