//#condition polish.usePolishGui && polish.doja

// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Sun Feb 29 19:10:56 CET 2004
package de.enough.polish.doja.rms;

/**
 * Thrown to indicate an operation could not be completed because the
 * record store could not be found.
 * <HR>
 * 
 * 
 * @since MIDP 1.0
 */
public class RecordStoreNotFoundException extends RecordStoreException
{
	/**
	 * Constructs a new <code>RecordStoreNotFoundException</code> with the
	 * specified detail message.
	 * 
	 * @param message - the detail message
	 */
	public RecordStoreNotFoundException( String message)
	{
		//TODO implement RecordStoreNotFoundException
	}

	/**
	 * Constructs a new <code>RecordStoreNotFoundException</code>
	 * with no detail message.
	 */
	public RecordStoreNotFoundException()
	{
		//TODO implement RecordStoreNotFoundException
	}

}
