//#condition polish.android
// generated by de.enough.doc2java.Doc2Java (www.enough.de) on Tue Mar 25 12:43:45 CET 2008
package de.enough.polish.android.rms;

/**
 * Thrown to indicate an operation could not be completed because the
 * record store system storage is full.
 */
public class RecordStoreFullException extends RecordStoreException
{
	/**
	 * Constructs a new <code>RecordStoreFullException</code> with the
	 * specified detail message.
	 * <P>
	 * 
	 * @param message - the detail message
	 */
	public RecordStoreFullException( String message)
	{
		super( message );
	}

	/**
	 * Constructs a new <code>RecordStoreFullException</code> with no detail
	 * message.
	 * <P>
	 * 
	 * 
	 */
	public RecordStoreFullException()
	{
		super();
	}

}
