#!/bin/bash
# starting the binary data editor:
java -classpath "%{INSTALL_PATH}/lib/enough-j2mepolish-build.jar:%{INSTALL_PATH}/lib/jdom.jar:$CLASSPATH" de.enough.polish.dataeditor.swing.SwingDataEditor $1 $2 $3